# Generated by Django 4.2.4 on 2023-09-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeaccount',
            name='income_names',
        ),
        migrations.RemoveField(
            model_name='financeaccount',
            name='incomes',
        ),
        migrations.RemoveField(
            model_name='financeaccount',
            name='new_expenses',
        ),
        migrations.RemoveField(
            model_name='financeaccount',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='financeaccount',
            name='saved_expense_value',
        ),
        migrations.AddField(
            model_name='financeaccount',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financeaccount',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financeaccount',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
