# Generated by Django 4.2.4 on 2023-09-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_account', '0002_remove_financeaccount_income_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeaccount',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
