# Generated by Django 4.2.4 on 2023-09-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_account', '0003_alter_financeaccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeaccount',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
