# Generated by Django 4.2.4 on 2023-09-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_account', '0004_alter_financeaccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeaccount',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
